---
title: "Code goes here"
author: "Kendra Swanson, Margaret Perry"
date: "April 30, 2017"
output: html_document
---

```{r}
library(tidyverse)
library(macleish)
library(rvest)
library(rgdal)
library(rgeos)
```

```{r}
names(macleish_layers)
```

```{r}
##Getting trail data
url1 <- "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/dcrtrails.html"
download.file(url1, destfile = basename(url1))
unzip("dcrtrails.zip", exdir = "dcrtrails")
```

```{r}
trails <- path.expand("dcrtrails")
#ogrListLayers(trails)
```

```{r}
dcr_trails <- readOGR(trails, "DCR_ROADS_TRAILS_ARC")
#summary(dcr_trails)
```

```{r}
##Getting college data
url_colleges<- "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/colleges.html"
download.file(url_colleges, destfile = basename(url_colleges))
unzip("colleges.zip", exdir = "colleges")
```

```{r}
colleges <- path.expand("colleges")
#ogrListLayers(colleges)
```

```{r}
colleges_loc<- readOGR(colleges, "COLLEGES_PT")
#summary(colleges_loc)
```

```{r}
##Getting contour data
url_contour <- "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/hp250k.html"
download.file(url_contour, destfile = basename(url_contour))
unzip("contours250k.zip", exdir = "contours")
```

```{r}
contours <- path.expand("contours")
#ogrListLayers(contours)
```

```{r}
contour_mass<- readOGR(contours, "CONTOURS250K_ARC")
#summary(contour_mass)
```

```{r}
##Transforming to coordinates that work in leaflet
dcr_trails <- spTransform(dcr_trails, CRS("+init=epsg:4326"))
contour_mass <- spTransform(contour_mass, CRS("+init=epsg:4326"))
colleges_loc <- spTransform(colleges_loc, CRS("+init=epsg:4326"))
```

```{r}
##Demonstration
library(leaflet)
leaflet() %>%
  addTiles() %>%
  addMarkers( data = colleges_loc, 
    popup = "+init=epsg:4326")
```



```{r}
library(sp)
coords <- rbind(c(42.458299, -72.710239),
                c(42.457476, -72.605017),
                c(42.316596, -72.601298),
                c(42.312746, -72.709123),
                c(42.458299, -72.710239)) %>%
  as.data.frame() %>%
  rename(lat = V1, lon = V2)
```

```{r}
polygon <- coords %>%
  select(lon,lat) %>%
  Polygon()
```

```{r}
sp_polygon <- SpatialPolygons(list(Polygons(list(polygon), ID = "a")))
```

```{r}
proj4string(sp_polygon) <- CRS("+init=epsg:4326")
```


```{r}
library(leaflet)
leaflet() %>%
  addTiles() %>%
  addPolylines(data = sp_polygon)
```

```{r}
contours_relevant <- gIntersection(sp_polygon, contour_mass)
```

```{r}
summary(contour_mass)
```

```{r}
summary(contours_relevant)
```

```{r}
trails_relevant <- gIntersection(sp_polygon, dcr_trails)
```

```{r}
library(leaflet)
mac_pal <- colorBin(palette = "Reds", domain = boundary$Shape_Leng)
leaflet() %>%
  addTiles() %>%
  addPolylines(data = contours_relevant, weight = 1)%>%
  addTiles()%>%
  addMarkers(data = colleges_loc, popup = "+init=epsg:4326")%>%
  addTiles()%>%
  addMarkers(data = macleish_layers[["buildings"]], 
             popup = ~ name, group = "Structures")

  addPolylines(data = trails_relevant) %>%
  addPolylines(data = contours_relevant, weight = 1) %>%
  addPolygons(data = boundary, color = ~mac_pal(Shape_Leng)) %>%
  addMarkers(data = colleges_loc)

```

```{r}

library(leaflet)
leaflet() %>%
  addTiles(group = "OpenStreetMap") %>%
  addProviderTiles("Esri.WorldImagery", group = "Satellite") %>%
  addTiles() %>%
  addPolylines(data = contours_relevant, weight = 1)%>%
  addTiles()%>%
  addMarkers(data = colleges_loc, popup = "+init=epsg:4326")%>%
  addTiles()%>%
  addMarkers(data = macleish_layers[["buildings"]], 
             popup = ~ name, group = "Structures")
```
Plan: 
-build a bunch of paths
-find elevation data
-pick easiest one and hardest one
```{r}
trail1_df <- rbind(c(42.320327, -72.640085),
                   c(42.324335, -72.648490),
                   c(42.331041, -72.652168),
                   c(42.334372, -72.653767),
                   c(42.335918, -72.664951),
                   c(42.336029, -72.669157),
                   c(42.337021, -72.672037),
                   c(42.349495, -72.670876),
                   c(42.355109, -72.673752),
                   c(42.360215, -72.671177),
                   c(42.362339, -72.671778),
                   c(42.367444, -72.670447),
                   c(42.369632, -72.674310),
                   c(42.373473, -72.675938),
                   c(42.376707, -72.674908),
                   c(42.381684, -72.676797),
                   c(42.383206, -72.679286),
                   c(42.386528, -72.679240),
                   c(42.394298, -72.676992),
                   c(42.399369, -72.677894),
                   c(42.408527, -72.669718),
                   c(42.410903, -72.668946),
                   c(42.412941, -72.667748),
                   c(42.415080, -72.668070),
                   c(42.416474, -72.667812),
                   c(42.422388, -72.669537),
                   c(42.423410, -72.671167),
                   c(42.424194, -72.671200),
                   c(42.426677, -72.668810),
                   c(42.429433, -72.669197),
                   c(42.430898, -72.670280),
                   c(42.431642, -72.672415),
                   c(42.432109, -72.677662),
                   c(42.436971, -72.679475),
                   c(42.438159, -72.681374),
                   c(42.439378, -72.681256),
                   c(42.442229, -72.681846),
                   c(42.444493, -72.680848),
                   c(42.447509, -72.680773)) %>%
  as.data.frame() %>%
  rename(lat = V1, lon = V2)
```

write function to convert df of coordinates to spatial lines df
```{r}
df_to_sp <- function(trail_df) {
  trail_df %>%
  # reverse order of columns
  select(lon, lat) %>%
  Line() %>%
  list() %>%
  Lines(ID = "a") %>%
  list() %>%
  SpatialLines()
}
```

```{r}
trail1_sp_fn <- df_to_sp(trail1_df)
```

```{r}
proj4string(trail1_sp_fn) <- CRS("+init=epsg:4326")
```

```{r}
leaflet() %>%
  addTiles() %>%
  addPolylines(data = trail1_sp_fn)

```

```{r}
trail2_df <- rbind(c(42.446700,-72.680977),
                   c(42.444812,-72.680676),
                   c(42.442813,-72.681880),
                   c(42.441125,-72.681662),
                   c(42.441149,-72.683609),
                   c(42.438132,-72.682311),
                   c(42.438048,-72.682700),
                   c(42.437940,-72.683073),
                   c(42.437162,-72.683787),
                   c(42.437019,-72.683949),
                   c(42.436552,-72.685490),
                   c(42.436372,-72.686804),
                   c(42.435259,-72.688848),
                   c(42.435175,-72.689286),
                   c(42.435067,-72.689448),
                   c(42.433367,-72.694201),
                   c(42.433080,-72.694898),
                   c(42.432805, -72.697056),
                   c(42.431751, -72.700543),
                   c(42.431008, -72.702855),
                   c(42.429979, -72.705751),
                   c(42.429567, -72.707629),
                   c(42.428149, -72.709574),
                   c(42.422682, -72.713384),
                   c(42.422213, -72.713569),
                   c(42.417057, -72.714204),
                   c(42.416569, -72.714600),
                   c(42.414847, -72.716427),
                   c(42.412999, -72.717504),
                   c(42.407875, -72.716490),
                   c(42.405987, -72.715070),
                   c(42.405742, -72.714705),
                   c(42.405749, -72.714675),
                   c(42.404301, -72.713720),
                   c(42.402995, -72.713418),
                   c(42.395556, -72.713087),
                   c(42.393633, -72.713197),
                   c(42.393432, -72.713338),
                   c(42.392831, -72.713931),
                   c(42.391836, -72.715218),
                   c(42.391695, -72.715590),
                   c(42.390781, -72.716223),
                   c(42.389838, -72.716686),
                   c(42.387790, -72.717523),
                   c(42.387561, -72.717744),
                   c(42.384050, -72.716222),
                   c(42.382391, -72.714305),
                   c(42.380595, -72.707471),
                   c(42.380119, -72.706902),
                   c(42.376910, -72.706012),
                   c(42.374793, -72.703555),
                   c(42.373161, -72.699279),
                   c(42.372242, -72.695857),
                   c(42.371647, -72.695170),
                   c(42.368579, -72.693754),
                   c(42.367208, -72.693646),
                   c(42.363696, -72.694118),
                   c(42.362436, -72.693947),
                   c(42.360795, -72.693110),
                   c(42.349743, -72.690009),
                   c(42.349188, -72.689644),
                   c(42.349029, -72.689912),
                   c(42.346008, -72.684162),
                   c(42.345643, -72.683722),
                   c(42.344977, -72.683068),
                   c(42.343772, -72.681405),
                   c(42.343692, -72.680643),
                   c(42.343280, -72.680085),
                   c(42.336964, -72.671974),
                   c(42.336311, -72.670296),
                   c(42.335037, -72.657508),
                   c(42.333258, -72.647790),
                   c(42.328522, -72.636040),
                   c(42.328189, -72.635675),
                   c(42.320142, -72.634495),
                   c(42.319505, -72.635634),
                   c(42.318913, -72.636158))%>%
  as.data.frame() %>%
  rename(lat = V1, lon = V2)
```

```{r}
trail2_sp_fn <- df_to_sp(trail2_df)
```

```{r}
proj4string(trail2_sp_fn) <- CRS("+init=epsg:4326")
```

```{r}
leaflet() %>%
  addTiles() %>%
  addPolylines(data = trail2_sp_fn)%>%
  addPolylines(data = trail1_sp_fn)

```
